### ISSUE TITLE
help is not customizable 

### ISSUE THREAD

**Issue by shime** [wjessop/trollop#5]
currently there is no way to customize the help message, only banner. I find it annoying that my argument parser takes liberty of defining how a help message will look on my CLI utility.

**Comment by wjessop** [comment]
This is my Github copy of the project (created as there was no copy on Github originally and I wanted to add this https://github.com/wjessop/trollop/commit/f00ef8d810ae4c99c2f3471f70aed5f0b53dc80d).

See the top three links at the top of the README file for the original project, it'd be best if you created a patch for that project, submitted it, then I will then pull into this copy.
