### ISSUE TITLE
Add information for all available options in README.md

### ISSUE THREAD

**Issue by BennyHallett** [wjessop/trollop#6]
I've found myself recently digging through the trollop code to find out how all the available options work when calling the `opt` method.

I think it'd be good to update the README.md file to include some more examples of what is available.

I'm happy to contribute these changes.

**Comment by wjessop** [comment]
Hey Benny,

Sorry I didn't get back to you yesterday, was busy with [this](https://news.ycombinator.com/item?id=8953545).

Thanks for the patches, but you should send your patches for trollop to William Morgan (https://github.com/wmorgan/trollop). He maintains trollop, which is the upstream of this fork*.

Will.

* I created this copy as I wanted to add a particular commit a few years ago and there was no way of easily forking his code as it wasn't on Github, I've just seen that his code is on Github now so I'll add a note in the README.
